const questions = [
	{
		id: 1,
		question: "Thủ đô của Việt Nam là gì?",
		options: ["Hà Nội", "TP.HCM", "Đà Nẵng", "Huế"],
		correctAnswer: "Hà Nội",
		prize: 100000,
	},
	{
		id: 2,
		question: "Việt Nam có bao nhiêu tỉnh, thành phố trực thuộc Trung ương?",
		options: ["58", "60", "63", "65"],
		correctAnswer: "63",
		prize: 200000,
	},
	{
		id: 3,
		question: "Hành tinh nào gần Mặt Trời nhất?",
		options: ["Trái Đất", "Sao Kim", "Sao Thủy", "Sao Hỏa"],
		correctAnswer: "Sao Thủy",
		prize: 300000,
	},
	{
		id: 4,
		question: "1 mét bằng bao nhiêu centimet?",
		options: ["10 cm", "50 cm", "100 cm", "1000 cm"],
		correctAnswer: "100 cm",
		prize: 500000,
	},
	{
		id: 5,
		question: "Con vật nào được gọi là chúa sơn lâm?",
		options: ["Hổ", "Voi", "Sư tử", "Báo"],
		correctAnswer: "Hổ",
		prize: 1000000,
	},
	{
		id: 6,
		question: "Ai là tác giả của Truyện Kiều?",
		options: ["Nguyễn Du", "Nguyễn Trãi", "Hồ Xuân Hương", "Nam Cao"],
		correctAnswer: "Nguyễn Du",
		prize: 2000000,
	},
	{
		id: 7,
		question: "Nước nào có hình dạng giống chiếc ủng?",
		options: ["Pháp", "Ý", "Đức", "Tây Ban Nha"],
		correctAnswer: "Ý",
		prize: 4000000,
	},
	{
		id: 8,
		question: "Trong bảng chữ cái tiếng Anh có bao nhiêu chữ cái?",
		options: ["24", "25", "26", "27"],
		correctAnswer: "26",
		prize: 8000000,
	},
	{
		id: 9,
		question: "Hành tinh nào được gọi là Hành tinh Đỏ?",
		options: ["Sao Kim", "Sao Hỏa", "Sao Mộc", "Sao Thổ"],
		correctAnswer: "Sao Hỏa",
		prize: 14000000,
	},
	{
		id: 10,
		question: "Đại dương lớn nhất thế giới là đại dương nào?",
		options: ["Đại Tây Dương", "Ấn Độ Dương", "Bắc Băng Dương", "Thái Bình Dương"],
		correctAnswer: "Thái Bình Dương",
		prize: 22000000,
	},
	{
		id: 11,
		question: "Ai là người đầu tiên đặt chân lên Mặt Trăng?",
		options: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Elon Musk"],
		correctAnswer: "Neil Armstrong",
		prize: 30000000,
	},
	{
		id: 12,
		question: "Cơ quan nào trong cơ thể người có chức năng bơm máu?",
		options: ["Phổi", "Gan", "Tim", "Thận"],
		correctAnswer: "Tim",
		prize: 40000000,
	},
	{
		id: 13,
		question: "Thủ đô của Nhật Bản là gì?",
		options: ["Osaka", "Tokyo", "Kyoto", "Nagoya"],
		correctAnswer: "Tokyo",
		prize: 60000000,
	},
	{
		id: 14,
		question: "Loài động vật nào lớn nhất trên Trái Đất?",
		options: ["Voi châu Phi", "Cá nhà táng", "Cá voi xanh", "Hươu cao cổ"],
		correctAnswer: "Cá voi xanh",
		prize: 80000000,
	},
	{
		id: 15,
		question: "Hệ điều hành Android được phát triển chủ yếu bởi công ty nào?",
		options: ["Apple", "Microsoft", "Google", "Amazon"],
		correctAnswer: "Google",
		prize: 100000000,
	},
];

export default questions;