import { v7 as uuidv7 } from "uuid";

export const categories = [
	{ key: "phone", label: "Điện thoại" },
	{ key: "tablet", label: "Máy tính bảng" },
];

export const products = [
	{
		id: uuidv7(),
		category: "phone",
		name: "Samsung Galaxy Z Fold8 Ultra 5G 12GB 256GB",
		url: "/dien-thoai-samsung-galaxy-z-fold-8-ultra.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/s/a/samsung-galaxy-z-fold-8-violet-01.jpg",
		badge: "Hàng đặt trước",
		salePrice: 52990000,
		originalPrice: null,
		discountPercent: null,
		promotions: [{ type: "smember", text: "Smember giảm đến 530.000đ" }],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: null,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "iPhone 17 Pro Max 256GB | Chính hãng",
		url: "/iphone-17-pro-max.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-17-pro-max_3.jpg",
		badge: null,
		salePrice: 35990000,
		originalPrice: 37990000,
		discountPercent: 5,
		promotions: [{ type: "smember", text: "Smember giảm đến 360.000đ" }],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 6 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "Samsung Galaxy Z Fold8 5G 12GB 256GB",
		url: "/dien-thoai-samsung-galaxy-z-fold-8.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/s/a/samsung-galaxy-z-fold-8-lavender-01.jpg",
		badge: "Hàng đặt trước",
		salePrice: 46990000,
		originalPrice: null,
		discountPercent: null,
		promotions: [{ type: "smember", text: "Smember giảm đến 470.000đ" }],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: null,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "Samsung Galaxy S26 Ultra 5G 12GB 256GB",
		url: "/dien-thoai-samsung-galaxy-s26-ultra.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/s/a/samsung-galaxy-s26-ultra-1.jpg",
		badge: null,
		salePrice: 30890000,
		originalPrice: 36990000,
		discountPercent: 16,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 309.000đ" },
			{ type: "student", text: "S-Student giảm thêm 500.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "Samsung Galaxy Z Fold7 12GB 256GB",
		url: "/dien-thoai-samsung-galaxy-z-fold-7.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/s/a/samsung-galaxy-z-fold-7.jpg",
		badge: null,
		salePrice: 41990000,
		originalPrice: 46990000,
		discountPercent: 11,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 420.000đ" },
			{ type: "student", text: "S-Student giảm thêm 500.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "iPhone 17 Pro 256GB | Chính hãng",
		url: "/iphone-17-pro.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-17-pro-256-gb.png",
		badge: null,
		salePrice: 33890000,
		originalPrice: 34990000,
		discountPercent: 3,
		promotions: [{ type: "smember", text: "Smember giảm đến 339.000đ" }],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 6 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "iPhone 17 256GB | Chính hãng",
		url: "/iphone-17-256gb.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone_17_256gb-3_2.jpg",
		badge: null,
		salePrice: 23990000,
		originalPrice: 24990000,
		discountPercent: 4,
		promotions: [{ type: "smember", text: "Smember giảm đến 240.000đ" }],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 6 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "Samsung Galaxy A17 5G 8GB 128GB",
		url: "/dien-thoai-samsung-galaxy-a17-5g.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/s/a/samsung-galaxy-a17-5g-back.jpg",
		badge: null,
		salePrice: 6790000,
		originalPrice: 7090000,
		discountPercent: 4,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 68.000đ" },
			{ type: "student", text: "S-Student giảm thêm 339.500đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 4.5,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "iPhone Air 256GB | Chính hãng",
		url: "/iphone-air-256gb.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone_air-3_2.jpg",
		badge: null,
		salePrice: 22990000,
		originalPrice: 31990000,
		discountPercent: 28,
		promotions: [{ type: "smember", text: "Smember giảm đến 230.000đ" }],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 6 tháng",
		shippingTime: "2 Giờ",
		rating: 4.9,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "OPPO Reno16 F 5G 8GB 256GB",
		url: "/dien-thoai-oppo-reno16-f.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-reno16f-pop-white-9.jpg",
		badge: "Hàng mới về",
		salePrice: 15490000,
		originalPrice: 15990000,
		discountPercent: 3,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 155.000đ" },
			{ type: "student", text: "S-Student giảm thêm 300.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "Nubia Neo 5 5G 8GB 128GB",
		url: "/dien-thoai-nubia-neo-5-5g.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-nubia-neo-5-5g-den.jpg",
		badge: null,
		salePrice: 6990000,
		originalPrice: 7490000,
		discountPercent: 7,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 70.000đ" },
			{ type: "student", text: "S-Student giảm thêm 300.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "Samsung Galaxy S26 5G 12GB 256GB",
		url: "/dien-thoai-samsung-galaxy-s26.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/s/a/samsung-galaxy-s26-10.jpg",
		badge: null,
		salePrice: 21490000,
		originalPrice: 25990000,
		discountPercent: 17,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 215.000đ" },
			{ type: "student", text: "S-Student giảm thêm 500.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "Xiaomi Redmi Note 14 Pro Plus 5G 8GB 256GB",
		url: "/dien-thoai-xiaomi-redmi-note-14-pro-plus.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/x/i/xiaomi-redmi-note-14-pro-plus.jpg",
		badge: null,
		salePrice: 8490000,
		originalPrice: 10800000,
		discountPercent: 21,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 85.000đ" },
			{ type: "student", text: "S-Student giảm thêm 300.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 4.7,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "Samsung Galaxy A07 5G 4GB 128GB",
		url: "/dien-thoai-samsung-galaxy-a07-5g.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/s/a/samsung-galaxy-a07-5g-2_3.jpg",
		badge: null,
		salePrice: 4790000,
		originalPrice: 5090000,
		discountPercent: 6,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 48.000đ" },
			{ type: "student", text: "S-Student giảm thêm 239.500đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "Samsung Galaxy A57 5G 8GB 128GB",
		url: "/dien-thoai-samsung-galaxy-a57.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-samsung-galaxy-a57-2.jpg",
		badge: null,
		salePrice: 11190000,
		originalPrice: 12490000,
		discountPercent: 10,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 112.000đ" },
			{ type: "student", text: "S-Student giảm thêm 500.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 4.9,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "POCO X8 Pro Max 12GB 256GB",
		url: "/dien-thoai-xiaomi-poco-x8-pro-max.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/x/i/xiaomi-poco-x8-pro-max_2.jpg",
		badge: null,
		salePrice: 13790000,
		originalPrice: 16990000,
		discountPercent: 19,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 138.000đ" },
			{ type: "student", text: "S-Student giảm thêm 300.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "OPPO Reno15 F 5G 8GB 256GB",
		url: "/dien-thoai-oppo-reno15-f.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-reno15f-5g.jpg",
		badge: null,
		salePrice: 11990000,
		originalPrice: null,
		discountPercent: null,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 120.000đ" },
			{ type: "student", text: "S-Student giảm thêm 300.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: null,
		rating: null,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "iPhone 15 128GB | Chính hãng VN/A",
		url: "/iphone-15.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-plus_1__1.png",
		badge: null,
		salePrice: 17990000,
		originalPrice: 19990000,
		discountPercent: 10,
		promotions: [{ type: "smember", text: "Smember giảm đến 180.000đ" }],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 6 tháng",
		shippingTime: "2 Giờ",
		rating: 4.9,
	},
	{
		id: uuidv7(),
		category: "phone",
		name: "Samsung Galaxy S25 Plus 256GB",
		url: "/dien-thoai-samsung-galaxy-s25-plus.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-samsung-galaxy-s25-plus_3_.png",
		badge: null,
		salePrice: 19990000,
		originalPrice: 26500000,
		discountPercent: 25,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 200.000đ" },
			{ type: "student", text: "S-Student giảm thêm 500.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},

	// ==========================================
	//            MÁY TÍNH BẢNG
	// ==========================================
	{
		id: uuidv7(),
		category: "tablet",
		name: "Lenovo Idea Tab Pro Gen 2 Matte Edition 8GB 256GB ZAHD0452VN - Kèm bút, bàn phím",
		url: "/may-tinh-bang-lenovo-idea-tab-pro-gen-2-zahd0452vn-kem-but-ban-phim.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/m/a/may-tinh-bang-lenovo-legion-tab-pro-gen-2-zahd0452vn-kem-but-ban-phim.jpg",
		badge: null,
		salePrice: 16990000,
		originalPrice: null,
		discountPercent: null,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 170.000đ" },
			{ type: "student", text: "S-Student giảm thêm 500.000đ" },
			{
				type: "other",
				text: "CHUỘT LENOVO 350 BLUETOOTH SILENT và 2 km khác",
			},
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: null,
		rating: null,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "iPad Pro chip M5 11 inch Wifi 256GB | Chính hãng Apple Việt Nam",
		url: "/ipad-pro-m5-11-inch-256gb.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/i/p/ipad-pro-m5.jpg",
		badge: null,
		salePrice: 34590000,
		originalPrice: 35590000,
		discountPercent: 3,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 346.000đ" },
			{ type: "student", text: "S-Student giảm thêm 500.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: null,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "Xiaomi Redmi Pad 2 9.7 inch Wifi 4GB 64GB",
		url: "/may-tinh-bang-xiaomi-redmi-pad-2-9-7-inch.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/r/e/redmi-pad-2-9-7-inch.jpg",
		badge: null,
		salePrice: 4690000,
		originalPrice: 4990000,
		discountPercent: 6,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 47.000đ" },
			{ type: "student", text: "S-Student giảm thêm 234.500đ" },
			{
				type: "other",
				text: "Tặng phiếu mua hàng trị giá lên đến 300.000đ khi mua kèm Tai nghe Buds 8 Pro/8 Active và 4 km khác",
			},
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: null,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "Lenovo Legion Tab Gen 5 12GB 256GB",
		url: "/may-tinh-bang-lenovo-legion-tab-gen-5-12gb-256gb-zah20030vn.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/l/e/lenovo-legion-tab-gen-5_1.jpg",
		badge: null,
		salePrice: 23490000,
		originalPrice: 23990000,
		discountPercent: 2,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 235.000đ" },
			{ type: "student", text: "S-Student giảm thêm 500.000đ" },
			{
				type: "other",
				text: "Tặng túi Legion Sling Bag trị giá 990,000 và 1 km khác",
			},
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: null,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "Samsung Galaxy Tab S10 Lite Wifi 6GB 128GB",
		url: "/may-tinh-bang-samsung-galaxy-tab-s10-lite-wifi.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/m/a/may-tinh-bang-samsung-galaxy-tab-a11-plus-wifi_2.jpg",
		badge: null,
		salePrice: 8390000,
		originalPrice: 9990000,
		discountPercent: 16,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 84.000đ" },
			{ type: "student", text: "S-Student giảm thêm 671.200đ" },
			{
				type: "other",
				text: "Giảm thêm đến 5 triệu đồng cho Tivi/Màn hình Samsung khi mua iPad/Tablet Samsung và 1 km khác",
			},
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: null,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "Huawei MatePad SE 11 inch Wifi 8GB 128GB",
		url: "/may-tinh-bang-huawei-matepad-se-11-8gb-128gb.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/h/u/huawei-matepad-se-11-inch_1_1.jpg",
		badge: null,
		salePrice: 6490000,
		originalPrice: 8790000,
		discountPercent: 26,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 65.000đ" },
			{ type: "student", text: "S-Student giảm thêm 300.000đ" },
			{
				type: "other",
				text: "Chi thêm 200K - Nhận ngay dịch vụ Bảo hành Vip 12 tháng 1 đổi 1 tại CellphoneS và 4 km khác",
			},
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: null,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "Lenovo Idea Tab Plus Matte Edition Wifi 8GB 128GB ZAG70981VN - Kèm bút, bàn phím",
		url: "/may-tinh-bang-lenovo-idea-tab-plus-wifi-8gb-128gb-zag70981vn-kem-but-ban-phim.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/l/e/lenovo-idea-tab-plus-wifi_1.jpg",
		badge: null,
		salePrice: 9890000,
		originalPrice: null,
		discountPercent: null,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 99.000đ" },
			{ type: "student", text: "S-Student giảm thêm 494.500đ" },
			{
				type: "other",
				text: "Tặng tai nghe Không dây Anker Soundcore R60I NC - A3959 ĐEN và 1 km khác",
			},
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "Huawei MatePad 11.5 S 2026 12GB 256GB - Kèm bàn phím",
		url: "/may-tinh-bang-huawei-matepad-11-5-s-2026.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/h/u/huawei-matepad-11-5-s-2026_1.jpg",
		badge: null,
		salePrice: 15590000,
		originalPrice: 18490000,
		discountPercent: 16,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 156.000đ" },
			{ type: "student", text: "S-Student giảm thêm 300.000đ" },
			{ type: "other", text: "PMH 2,000,000₫" },
			{
				type: "other",
				text: "Chi thêm 350K - Nhận ngay dịch vụ Bảo hành Vip 12 tháng 1 đổi 1 tại CellphoneS và 6 km khác",
			},
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 4.6,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "Lenovo Yoga Tab Wifi 12GB 256GB TB710 ZAG60105VN - Kèm bút, bàn phím",
		url: "/may-tinh-bang-lenovo-yoga-tab-tb710.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/l/e/lenovo-yoga-tab-tb710-4_1.jpg",
		badge: null,
		salePrice: 17990000,
		originalPrice: null,
		discountPercent: null,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 180.000đ" },
			{ type: "student", text: "S-Student giảm thêm 500.000đ" },
			{
				type: "other",
				text: "Giảm đến 1 triệu khi thanh toán qua thẻ tín dụng HSBC và 2 km khác",
			},
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 4.9,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "iPad A16 Wifi 128GB 2025 | Chính hãng Apple Việt Nam",
		url: "/ipad-a16-11-inch.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/i/p/ipad-a16-11-inch_10_.jpg",
		badge: null,
		salePrice: 12490000,
		originalPrice: 12790000,
		discountPercent: 2,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 125.000đ" },
			{ type: "student", text: "S-Student giảm thêm 500.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "iPad mini 7 2024 Wifi 128GB | Chính hãng Apple Việt Nam",
		url: "/ipad-mini-7.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_ng_n_13_7.png",
		badge: null,
		salePrice: 14690000,
		originalPrice: 16490000,
		discountPercent: 11,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 147.000đ" },
			{ type: "student", text: "S-Student giảm thêm 500.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "Máy đọc sách Boox Savi 6S",
		url: "/may-doc-sach-boox-savi-6s.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/m/a/may-doc-sach-boox-savi-6s-1.jpg",
		badge: null,
		salePrice: 3390000,
		originalPrice: 3990000,
		discountPercent: 15,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 68.000đ" },
			{ type: "student", text: "S-Student giảm thêm 169.500đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: null,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "Xiaomi Pad Mini 8GB 256GB",
		url: "/may-tinh-bang-xiaomi-pad-mini.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/x/i/xiaomi-pad-mini.jpg",
		badge: null,
		salePrice: 13490000,
		originalPrice: 15990000,
		discountPercent: 16,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 135.000đ" },
			{ type: "student", text: "S-Student giảm thêm 300.000đ" },
			{
				type: "other",
				text: "Tặng phiếu mua hàng trị giá lên đến 300.000đ khi mua kèm Tai nghe Buds 8 Pro/8 Active và 4 km khác",
			},
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "HONOR Pad 10 Wifi 8GB 256GB",
		url: "/may-tinh-bang-honor-pad-10.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/h/o/honnor-pad-10.jpg",
		badge: null,
		salePrice: 10990000,
		originalPrice: null,
		discountPercent: null,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 110.000đ" },
			{ type: "student", text: "S-Student giảm thêm 500.000đ" },
			{
				type: "other",
				text: "Tặng bút cảm ứng thông minh Honor và 5 km khác",
			},
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "iPad A16 Wifi 256GB 2025 | Chính hãng Apple Việt Nam",
		url: "/ipad-a16-11-inch-256gb.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/i/p/ipad-a16-11-inch_10__1.jpg",
		badge: null,
		salePrice: 15290000,
		originalPrice: 15590000,
		discountPercent: 2,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 153.000đ" },
			{ type: "student", text: "S-Student giảm thêm 500.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "Huawei MatePad 11.5 2026 8GB 128GB, Kèm bàn phím",
		url: "/may-tinh-bang-huawei-matepad-11-5-2026-8gb-128gb-kem-ban-phim.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/h/u/huawei-matepad-11-5-2026-8gb-128gb-kem-ban-phim.jpg",
		badge: "Hàng mới về",
		salePrice: 9990000,
		originalPrice: 10490000,
		discountPercent: 5,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 100.000đ" },
			{ type: "student", text: "S-Student giảm thêm 300.000đ" },
			{
				type: "other",
				text: "Tặng chuột Bluetooth Huawei CD26 trị giá 499,000 và 5 km khác",
			},
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: null,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "Xiaomi Redmi Pad 2 Wifi 6GB 128GB",
		url: "/may-tinh-bang-xiaomi-redmi-pad-2-wifi.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/x/i/xiaomi-redmi-pad-2-wifi-1.jpg",
		badge: null,
		salePrice: 6190000,
		originalPrice: 6690000,
		discountPercent: 7,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 62.000đ" },
			{ type: "student", text: "S-Student giảm thêm 300.000đ" },
			{
				type: "other",
				text: "Tặng phiếu mua hàng trị giá lên đến 300.000đ khi mua kèm Tai nghe Buds 8 Pro/8 Active và 4 km khác",
			},
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "Huawei MatePad Papermatte 11.5 inch 2025 8GB 256GB - Kèm bàn phím ",
		url: "/may-tinh-bang-huawei-matepad-papermate-11-5-inch.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/h/u/huawei-matepad-papermate-11-5-inch_1_2.jpg",
		badge: null,
		salePrice: 11990000,
		originalPrice: 13490000,
		discountPercent: 11,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 120.000đ" },
			{ type: "student", text: "S-Student giảm thêm 300.000đ" },
			{ type: "other", text: "PMH 1,500,000₫" },
			{
				type: "other",
				text: "Bộ ứng dụng Văn phòng WPS 3.0, Huawei Notes, App Gallery . Hướng dẫn cài đặt WPS 3.0 và google play và 7 km khác",
			},
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "iPad Air 11 inch M3 Wifi 128GB 2025 | Chính hãng Apple Việt Nam",
		url: "/apple-ipad-air-m3.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/i/p/ipad-air-11-wifi-1.jpg",
		badge: null,
		salePrice: 18990000,
		originalPrice: 21490000,
		discountPercent: 12,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 190.000đ" },
			{ type: "student", text: "S-Student giảm thêm 500.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: null,
	},
	{
		id: uuidv7(),
		category: "tablet",
		name: "iPad Air 11 inch M4 Wifi 128GB 2026 | Chính hãng ",
		url: "/apple-ipad-air-m4-11-inch-128gb-wifi.html",
		image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/1/_/1_1__1_1.png",
		badge: null,
		salePrice: 19690000,
		originalPrice: 20990000,
		discountPercent: 6,
		promotions: [
			{ type: "smember", text: "Smember giảm đến 197.000đ" },
			{ type: "student", text: "S-Student giảm thêm 500.000đ" },
		],
		installmentDetail:
			"Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
		shippingTime: "2 Giờ",
		rating: 5,
	},
];
